#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use 5.010;
use strict;
use warnings;

use Org::Parser;

my $org = Org::Parser->new;
my $doc;
{
    local $/;
    $doc = $org->parse(~~<>);
}

my $n = 0;
$doc->walk(
    sub {
        my $el = shift;
        $n++ if $el->isa('Org::Element::Headline') &&
            $el->is_todo && !$el->is_done;
    });

say $n;

# ABSTRACT: Count todos which are undone in Org document
# PODNAME:

=head1 SYNOPSIS

 % count-undone-org-todos todo.org
 42

which is equivalent to:

 % list-org-todos todo.org | wc -l
 % list-org-todos --nodone todo.org | wc -l


=head1 SEE ALSO

L<Org::Parser>

L<count-done-org-todos>

L<count-org-todos>

L<list-org-todos>

=cut
