#!perl

use 5.010;
use strict;
use warnings;

use Org::Parser;

# AUTHORITY
# DATE
# DIST
# VERSION

my $org = Org::Parser->new;
my $doc;
{
    local $/;
    $doc = $org->parse(scalar <>);
}

my $n = 0;
$doc->walk(
    sub {
        my $el = shift;
        $n++ if $el->isa('Org::Element::Headline') && $el->is_todo;
    });

say $n;

# ABSTRACT: Count todos in Org document
# PODNAME:

=head1 SYNOPSIS

 % count-org-todos todo.org
 101


=head1 SEE ALSO

L<Org::Parser>

L<count-done-org-todos>

L<count-undone-org-todos>

=cut
